### ISSUE TITLE
If AJ_Tools_UT_assert throws a assert error, it should display a better message.

### ISSUE THREAD

**Issue by creativeArtie** [AJARProject/AJ_Tools_UnitTest#2]
If there are thousands of tests, each with dozens of assert tests, how do I figure out what assert in which test method throws this error? 

![Screenshot 2021-01-28 154020](https://user-images.githubusercontent.com/19804069/106213821-626ebf80-6182-11eb-83cd-4b5a886a36de.png)

Please add the method name and a assert number with in the ASSERT message.

**Comment by Ganbin** [comment]
The latest release contain this change. Let me know if this work on your side
https://github.com/AJARProject/AJ_Tools_UnitTest/releases/latest

**Comment by creativeArtie** [comment]
It work on my side
